@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.nayrus.noteblockmaster.utils;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;