@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.nayrus.noteblockmaster.datagen.recipes;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;