@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.nayrus.noteblockmaster.network.payload;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;