@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.nayrus.noteblockmaster.datagen;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;